### Find All Babysitters
GET http://localhost:8080/api/babysitters

### Find Babysitter By ID
GET http://localhost:8080/api/babysitters/2


### Create new babysitter
POST http://localhost:8080/api/babysitters
Content-Type: application/json

{
  "id": 11,
  "firstName": "Tanya",
  "lastName": "Smith",
  "zipCode": 55446,
  "yearsOfExperience": 6,
  "hourlyRate": 15,
  "location": "OUTDOOR"
}

### Create new Run with invalid dates (completedOn is before startedOn)
POST http://localhost:8080/api/babysitters
Content-Type: application/json

{
  "id": 11,
  "firstName": "Tanya",
  "lastName": "Smith",
  "zipCode": 55446,
  "yearsOfExperience": 6,
  "hourlyRate": 15,
  "location": "OUTDOOR"
}

### Update an existing Run
PUT http://localhost:8080/api/babysitters/11
Content-Type: application/json

{
  "id": 11,
  "firstName": "Tanya",
  "lastName": "Smith",
  "zipCode": 55446,
  "yearsOfExperience": 6,
  "hourlyRate": 15,
  "location": "OUTDOOR"
}

### Delete a Run
DELETE http://localhost:8080/api/babysitters/11
