### Find ALl Runs
GET http://localhost:8080/api/runs

### Find Run By ID
GET http://localhost:8080/api/runs/2

### Find Run By ID that doesn't exist
GET http://localhost:8080/api/runs/99


### Create new Run
POST http://localhost:8080/api/runs
Content-Type: application/json

{
  "id": 11,
  "title": "Saturday Morning Run"
}

### Create new Run with invalid title
POST http://localhost:8080/api/runs
Content-Type: application/json

{
  "id": 11,
  "title": ""
}

### Update an existing Run
PUT http://localhost:8080/api/runs/11
Content-Type: application/json

{
  "id": 11,
  "title": "UPDATED TITLE"
}

### Delete a Run
DELETE http://localhost:8080/api/runs/11